# Site settings
title: mattValdez
email: matvaldez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattvaldez.me" # the base hostname & protocol for your site
twitter_username: mattvaldez85
github_username:  mattvaldez

# Build settings
markdown: kramdown
